if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="notes-2";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

unitsize(1cm);
draw((-1,0)--(3,0));
draw((0,-1)--(0,3));
dot("$1$", (1,0), S);
dot("$i$", (0,1), W);
dot("$0$", (0,0), SW);
dot("$1+i$", (1,1), E);
draw((0,0)--(1,1), dashed+red);
dot("$1+2i$", (1,2), E);
draw((1,1)--(1,2), dashed+blue);
label("$\textrm{Re}$", (3,0), E);
label("$\textrm{Im}$", (0,3), N);
