if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="notes-18";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

unitsize(1.5cm);
draw(arc((0,0),0.3,0,150), arrow=EndArrow, red);
draw(arc((0,0),0.6, 0,45), arrow=EndArrow, blue);
draw(arc((0,0),0.6,45,150), arrow=EndArrow, magenta);
draw((0,0)--(2.5,0), EndArrow); label("$\mathrm{Re}$", (2.5,0), E);
pair z = 2*dir(150); pair w = 3*dir(45);
draw(z--(0,0), red);
draw((0,0)--w, blue);
dot("$z$", z, dir(150), red); dot("$w$", w, dir(45), blue);
label("$\alpha$", (0,0), dir(75), red);
label("$\beta$", (0,0), 8.4*dir(22.5), blue);
label("$\alpha-\beta$", (0,0), 8*dir(75+22.5), magenta);
dot((0,0));
