if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="notes-1";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

unitsize(2cm);
draw((-1.5,0)--(1.5,0));
draw((0,-1.5)--(0,1.5));
dot("$-1$", (-1,0), S);
pair alpha = dir(40);
dot((0,0));
draw(alpha--(0,0)--(-1,0)--cycle);
dot("$\tau_1\alpha$", alpha, NE);
dot("$\overline{\tau_1\alpha}$", dir(-40), SE);
draw(dir(-40)--(0,0)--(-1,0)--cycle);
